/**
 * Known type-ramp deviations (ux-v2 §2), frozen at OCL-89 and re-synced
 * after the parallel visual-fix cards in this mission landed.
 *
 * The board is mid-migration to the ux-v2 doctrine (OCL-34/35/36/37 and
 * the parallel visual-fix cards, e.g. OCL-83/85/92/93/94).
 * Every entry below is a real, currently-shipping font-size outside
 * 22/16/13/12/11px, captured so the guard (`type-ramp.test.ts`) can stay
 * green without pretending the migration is finished.
 *
 * This list only shrinks. Deleting an entry here is how a fix card proves
 * its work — the guard's second test fails if an entry lingers after the
 * CSS underneath it is gone. Adding an entry for a *new* violation is a
 * regression, not a fix, and should not happen without a doctrine
 * amendment (see docs/design/amendments.md).
 */
export const KNOWN_TYPE_RAMP_EXCEPTIONS: { file: string; selector: string; value: string }[] = [
  // app/globals.css
  { file: "app/globals.css", selector: ".meta", value: "14px" },
  { file: "app/globals.css", selector: "h1", value: "28px" },
  // app/insights/insights.css
  { file: "app/insights/insights.css", selector: ".nb .ins-cap-note", value: "10px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-legend", value: "10px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-cid", value: "10.5px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-empty-title", value: "15px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-foot", value: "10px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-group-line", value: "9px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-legend", value: "10px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-mark", value: "10px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-share-pct", value: "10px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-subtotals", value: "10px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-table td", value: "12.5px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-table td.num", value: "11.5px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-tile .ins-note", value: "10px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-tile .ins-note", value: "9.5px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-tile .ins-num", value: "19px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-tile .ins-num", value: "24px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-tile .ins-num", value: "28px" },
  { file: "app/insights/insights.css", selector: ".nb .ins-trend-axis", value: "9.5px" },
  // app/settings/project-context.module.css
  { file: "app/settings/project-context.module.css", selector: ".fieldLabel,\n.previewLabel", value: "9.5px" },
  // styles/nebula.css
  { file: "styles/nebula.css", selector: ".nb .am-opt", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .btn-back", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .btn-new", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .card .card-type", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .card .cid", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .card-foot", value: "10.5px" },
  { file: "styles/nebula.css", selector: ".nb .cli-name", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .cmd", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .col-head", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .conn .cap", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .conn .l2", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .copy", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .cover-list .cover-state", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-btn-ghost", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-btn-pri", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-btn-sec", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-check-expected", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-check-meta", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .d-check-num", value: "10.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-check-step", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-clock", value: "10.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-close", value: "15px" },
  { file: "styles/nebula.css", selector: ".nb .d-copy", value: "10.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-mission", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-progress", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .d-roles .rl", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-sec .md,\n.nb .md", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-sec p", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-status", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-textarea", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .d-verify-lbl", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .detail h3", value: "18px" },
  { file: "styles/nebula.css", selector: ".nb .detail h3", value: "20px" },
  { file: "styles/nebula.css", selector: ".nb .sk-detail h3", value: "20px" },
  { file: "styles/nebula.css", selector: ".nb .empty-col", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .exec .check", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .exec .logo", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .exec-add .logo", value: "14px" },
  { file: "styles/nebula.css", selector: ".nb .exec-add .models .input", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .exec-add .note", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .exec-pulse", value: "10.5px" },
  { file: "styles/nebula.css", selector: ".nb .field label", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .field label .opt", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .filter-result", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .fresh-tok .lbl", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .input", value: "13.5px" },
  { file: "styles/nebula.css", selector: ".nb .input.mono", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .logo", value: "15px" },
  { file: "styles/nebula.css", selector: ".nb .mchip", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .mchip-add", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .md h3,\n.nb .md-h", value: "17px" },
  { file: "styles/nebula.css", selector: ".nb .meta-cli-arrow", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .mf-create-head b,\n.nb .mf-create label > span,\n.nb .mf-create-preview > span", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .mission-context summary", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .mission-count", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .mission-header h1", value: "21px" },
  { file: "styles/nebula.css", selector: ".nb .mission-kicker > span:first-child,\n.nb .mission-form-label,\n.nb .mission-editor label > span", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .mission-status", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .ml-caret", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .ml-row .cid", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .ml-row .cli-name", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .page-sub", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .pf-box", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .pf-context-status", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .plug-lead", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .plug-state", value: "10.5px" },
  { file: "styles/nebula.css", selector: ".nb .policy .act", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .policy .act small", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .policy .act small.price-flag", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .policy .chain i", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .policy .who", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .policy .who small", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .policy td.who", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .policy td::before", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .policy th", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .policy-note", value: "10.5px" },
  { file: "styles/nebula.css", selector: ".nb .preview", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .preview .cap", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .rec-cover .rec-head .sec-cap", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .recipe .lbl", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .recipe textarea.d-mono", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .recipe textarea.input", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .release-chip", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .release-count", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .release-empty", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .release-header h1", value: "21px" },
  { file: "styles/nebula.css", selector: ".nb .release-kicker,\n.nb .release-rel-label", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .release-usage b", value: "14px" },
  { file: "styles/nebula.css", selector: ".nb .review-chip", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .sec-cap", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .seen-chip small", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .seen-note", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .selo", value: "8.5px" },
  { file: "styles/nebula.css", selector: ".nb .skip", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .steps-ind", value: "10.5px" },
  { file: "styles/nebula.css", selector: ".nb .steps-ind", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .tag", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .telemetry", value: "10.5px" },
  { file: "styles/nebula.css", selector: ".nb .tok .sub", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb .tok-cap", value: "9px" },
  { file: "styles/nebula.css", selector: ".nb .tok-note", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb .upd-cmd-row code", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .upd-mode-note", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .upd-state", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .upd-step", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .upd-step-name", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .upd-version", value: "11.5px" },
  { file: "styles/nebula.css", selector: ".nb .werr", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .wok", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb .wstep h2", value: "21px" },
  { file: "styles/nebula.css", selector: ".nb .wstep h2", value: "26px" },
  { file: "styles/nebula.css", selector: ".nb h1", value: "21px" },
  { file: "styles/nebula.css", selector: ".nb h1", value: "24px" },
  { file: "styles/nebula.css", selector: ".nb-auth .auth-err", value: "12.5px" },
  { file: "styles/nebula.css", selector: ".nb-auth .auth-err::before", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb-auth .auth-lead", value: "30px" },
  { file: "styles/nebula.css", selector: ".nb-auth .auth-mark", value: "15px" },
  { file: "styles/nebula.css", selector: ".nb-auth .auth-rule", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb-auth .brand", value: "10px" },
  { file: "styles/nebula.css", selector: ".nb-auth .foot", value: "9.5px" },
  { file: "styles/nebula.css", selector: ".nb-auth h1", value: "26px" },
];
