// AUTO-GENERATED by scripts/brand-icons.mjs — the identity lives there. Do not edit.
export const BRAND_ART = {
  stroke: 2,
  wordmark: {
    viewBox: "-0.5 0.5 102.8 21",
    trailOpacity: 0.55,
    lead: { d: "M1 14A5 5 0 1 0 11 14A5 5 0 1 0 1 14M16.4 8L21 20M21 20L25.6 8M30 14L40 14M40 14A5 5 0 1 0 38.536 17.536M45.4 8L45.4 20M45.4 12A4 4 0 0 1 49.4 8", dots: [] },
    trail: { d: "M62.736 10.464A5 5 0 1 0 62.736 17.536M69.6 2L69.6 20M75 8L75 20M88.936 10.464A5 5 0 1 0 88.936 17.536M95.4 2L95.4 20M100.8 8L95.4 13.4M95.4 13.4L100.8 20", dots: [{ cx: 75, cy: 4.3, r: 1 }] },
  },
  monogram: {
    viewBox: "0 0 32 32",
    stroke: 4.4,
    d: "M5 16A11 11 0 1 0 27 16A11 11 0 1 0 5 16",
    dots: [{ cx: 16, cy: 16, r: 4 }],
  },
} as const;
